"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ $username$hostname ](bg:#f6f6f6 fg:#000000)\
[](bg:#cfcfcf fg:#f6f6f6)\
$directory\
[](fg:#cfcfcf bg:#331e39)\
$git_branch\
$git_status\
[](fg:#331e39 bg:#331e9)\
$nodejs\
$golang\
$python\
\n$character
"""
[username]
disabled = false
show_always = true   # default anyway
style_user = "bg:#f6f6f6 fg:#000000"   # match your desired colors
style_root = "bg:#a3aed2 fg:#ff0000 bold"   # optional: different for root
format = '[ $user ]($style)'

[hostname]
ssh_only = false       # only show on remote/SSH
ssh_symbol = " "
format = "[$ssh_symbol$hostname]($style)"
style = "bg:#f6f6f6 fg:#000000"

[directory]
style = "fg:#000000 bg:#cfcfcf"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#331e9"
format = '[[ $symbol $branch ](fg:#775b80 bg:#331e39)]($style)'

[git_status]
style = "bg:#331e9"
format = '[[($all_status $ahead_behind )](fg:#775b80 bg:#331e39)]($style)'

[character]
success_symbol = '[\$](bold foreground)'
error_symbol   = '[\$](bold red)'
format         = '$symbol '
