# laser

[colors.primary]
background = "#030d18"
foreground = "#f106e3"

[colors.normal]
black = "#626262"
red = "#ff8373"
green = "#b4fb73"
yellow = "#09b4bd"
blue = "#fed300"
magenta = "#ff90fe"
cyan = "#d1d1fe"
white = "#f1f1f1"

[colors.bright]
black = "#8f8f8f"
red = "#ffc4be"
green = "#d6fcba"
yellow = "#fffed5"
blue = "#f92883"
magenta = "#ffb2fe"
cyan = "#e6e7fe"
white = "#ffffff"

