# rose pine

[colors.primary]
background = "#191724"
foreground = "#e0def4"

[colors.normal]
black = "#706e86"
red = "#eb6f92"
green = "#9ccfd8"
yellow = "#f6c177"
blue = "#31748f"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.bright]
black = "#706e86"
red = "#eb6f92"
green = "#9ccfd8"
yellow = "#f6c177"
blue = "#31748f"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

